# Generated by Django 3.1.7 on 2021-02-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('time_cre', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('time_upd', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
